name: Publish Python distributions to PyPI and/or TestPyPI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-n-publish:
    name: Publish Python distributions to PyPI and/or TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install build package
        run: pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: LS
        run: ls

  # # builds a docker container and pushes to heroku
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Docker Login
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #       run: docker login --username celmore25@gmail.com -p ${HEROKU_API_KEY} registry.heroku.com
  #     - name: Docker Build
  #       run: |
  #             echo registry.heroku.com/snakeweb/web
  #             docker build -t registry.heroku.com/snakeweb/web .
  #     - name: Push Docker Image
  #       run: |
  #             docker push registry.heroku.com/snakeweb/web